services:

    pages.controller.display:
        class: primetime\pages\controller\display
        arguments:
            - @request
            - @user
            - @template
            - @dbal.conn
            - @controller.helper
